# Generated by Django 5.2.1 on 2025-06-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='reset_password_exprie',
            new_name='reset_password_expire',
        ),
    ]
