# Generated by Django 5.2.1 on 2025-07-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(help_text='User height in centimeters')),
                ('weight', models.FloatField(help_text='User weight in kilograms')),
                ('size', models.CharField(help_text='Suitable size', max_length=10)),
            ],
        ),
    ]
